module.exports = function(opts){
  if(opts.key === 'York-2480'){
    return [
      {
        "user_name": "York-2480",
        "ancestors": [
          {
            "Id": 10147686,
            "Name": "York-2480",
            "FirstName": "Theodore Robert",
            "MiddleName": "",
            "LastNameAtBirth": "York",
            "LastNameCurrent": "York",
            "Nicknames": "",
            "LastNameOther": "",
            "RealName": "Theodore Robert",
            "Prefix": "",
            "Suffix": "",
            "BirthLocation": "Mitchel Field, Hempstead, New York, United States",
            "DeathLocation": "Sandy, Salt Lake, Utah, United States",
            "Gender": "Male",
            "BirthDate": "1926-05-04",
            "DeathDate": "2009-02-22",
            "BirthDateDecade": "1920's",
            "DeathDateDecade": "2000's",
            "Photo": "",
            "IsLiving": "0",
            "Father": "10147687",
            "Mother": "10147688",
            "Privacy": "40",
            "IsPerson": 1,
            "Touched": "20150327151354",
            "ShortName": "Theodore Robert York",
            "BirthNamePrivate": "Theodore Robert York",
            "LongNamePrivate": "Theodore Robert York",
            "LongName": "Theodore Robert  York",
            "BirthName": "Theodore Robert York",
            "Privacy_IsPrivate": false,
            "Privacy_IsPublic": false,
            "Privacy_IsOpen": false,
            "Privacy_IsAtLeastPublic": false,
            "Privacy_IsSemiPrivate": true,
            "Privacy_IsSemiPrivateBio": false
          },
          {
            "Id": "10147687",
            "Name": "Yurkiewicz-1",
            "FirstName": "Theodore",
            "MiddleName": "",
            "LastNameAtBirth": "Yurkiewicz",
            "LastNameCurrent": "Yurkiewicz",
            "Nicknames": null,
            "LastNameOther": null,
            "RealName": "Theodore",
            "Prefix": null,
            "Suffix": null,
            "BirthLocation": null,
            "DeathLocation": null,
            "Gender": "Male",
            "BirthDate": "1892-06-23",
            "DeathDate": "1955-10-22",
            "BirthDateDecade": "1890's",
            "DeathDateDecade": "1950's",
            "Photo": "",
            "IsLiving": null,
            "Father": "10147691",
            "Mother": "10147693",
            "Privacy": "60",
            "IsPerson": 1,
            "Touched": "20150504144641",
            "ShortName": "Theodore Yurkiewicz",
            "BirthNamePrivate": "Theodore Yurkiewicz",
            "LongNamePrivate": "Theodore Yurkiewicz",
            "LongName": "Theodore  Yurkiewicz",
            "BirthName": "Theodore Yurkiewicz",
            "Privacy_IsPrivate": false,
            "Privacy_IsPublic": false,
            "Privacy_IsOpen": true,
            "Privacy_IsAtLeastPublic": true,
            "Privacy_IsSemiPrivate": false,
            "Privacy_IsSemiPrivateBio": false
          },
          {
            "Id": "10147691",
            "Name": "Yurkiewicz-2",
            "FirstName": "Elias",
            "MiddleName": "",
            "LastNameAtBirth": "Yurkiewicz",
            "LastNameCurrent": "Yurkiewicz",
            "Nicknames": null,
            "LastNameOther": null,
            "RealName": "Elias",
            "Prefix": null,
            "Suffix": null,
            "BirthLocation": null,
            "DeathLocation": null,
            "Gender": "Male",
            "BirthDate": "1849-07-29",
            "DeathDate": "1936-00-00",
            "BirthDateDecade": "1840's",
            "DeathDateDecade": "1930's",
            "Photo": "",
            "IsLiving": null,
            "Father": null,
            "Mother": null,
            "Privacy": "60",
            "IsPerson": 1,
            "Touched": "20150504144641",
            "ShortName": "Elias Yurkiewicz",
            "BirthNamePrivate": "Elias Yurkiewicz",
            "LongNamePrivate": "Elias Yurkiewicz",
            "LongName": "Elias  Yurkiewicz",
            "BirthName": "Elias Yurkiewicz",
            "Privacy_IsPrivate": false,
            "Privacy_IsPublic": false,
            "Privacy_IsOpen": true,
            "Privacy_IsAtLeastPublic": true,
            "Privacy_IsSemiPrivate": false,
            "Privacy_IsSemiPrivateBio": false
          },
          {
            "Id": "10147693",
            "Name": "Zuk-32",
            "FirstName": "Xenia",
            "MiddleName": "",
            "LastNameAtBirth": "Zuk",
            "LastNameCurrent": "Zuk",
            "Nicknames": null,
            "LastNameOther": null,
            "RealName": "Xenia",
            "Prefix": null,
            "Suffix": null,
            "BirthLocation": null,
            "DeathLocation": null,
            "Gender": "Female",
            "BirthDate": "1857-03-29",
            "DeathDate": "1906-00-00",
            "BirthDateDecade": "1850's",
            "DeathDateDecade": "1900's",
            "Photo": "",
            "IsLiving": null,
            "Father": "10147714",
            "Mother": "10147715",
            "Privacy": "60",
            "IsPerson": 1,
            "Touched": "20150504144641",
            "ShortName": "Xenia Zuk",
            "BirthNamePrivate": "Xenia Zuk",
            "LongNamePrivate": "Xenia Zuk",
            "LongName": "Xenia  Zuk",
            "BirthName": "Xenia Zuk",
            "Privacy_IsPrivate": false,
            "Privacy_IsPublic": false,
            "Privacy_IsOpen": true,
            "Privacy_IsAtLeastPublic": true,
            "Privacy_IsSemiPrivate": false,
            "Privacy_IsSemiPrivateBio": false
          },
          {
            "Id": "10147714",
            "Name": "Zuk-33",
            "FirstName": "Nicolaus",
            "MiddleName": "",
            "LastNameAtBirth": "Zuk",
            "LastNameCurrent": "Zuk",
            "Nicknames": null,
            "LastNameOther": null,
            "RealName": "Nicolaus",
            "Prefix": null,
            "Suffix": null,
            "BirthLocation": null,
            "DeathLocation": null,
            "Gender": "Male",
            "BirthDate": "1830-00-00",
            "DeathDate": "0000-00-00",
            "BirthDateDecade": "1830's",
            "DeathDateDecade": "unknown",
            "Photo": "",
            "IsLiving": null,
            "Father": null,
            "Mother": null,
            "Privacy": "60",
            "IsPerson": 1,
            "Touched": "20150504144641",
            "ShortName": "Nicolaus Zuk",
            "BirthNamePrivate": "Nicolaus Zuk",
            "LongNamePrivate": "Nicolaus Zuk",
            "LongName": "Nicolaus  Zuk",
            "BirthName": "Nicolaus Zuk",
            "Privacy_IsPrivate": false,
            "Privacy_IsPublic": false,
            "Privacy_IsOpen": true,
            "Privacy_IsAtLeastPublic": true,
            "Privacy_IsSemiPrivate": false,
            "Privacy_IsSemiPrivateBio": false
          },
          {
            "Id": "10147715",
            "Name": "Butka-6",
            "FirstName": "Anna",
            "MiddleName": "",
            "LastNameAtBirth": "Butka",
            "LastNameCurrent": "Butka",
            "Nicknames": null,
            "LastNameOther": null,
            "RealName": "Anna",
            "Prefix": null,
            "Suffix": null,
            "BirthLocation": null,
            "DeathLocation": null,
            "Gender": "Female",
            "BirthDate": "1827-00-00",
            "DeathDate": "0000-00-00",
            "BirthDateDecade": "1820's",
            "DeathDateDecade": "unknown",
            "Photo": "",
            "IsLiving": null,
            "Father": null,
            "Mother": null,
            "Privacy": "60",
            "IsPerson": 1,
            "Touched": "20150504144641",
            "ShortName": "Anna Butka",
            "BirthNamePrivate": "Anna Butka",
            "LongNamePrivate": "Anna Butka",
            "LongName": "Anna  Butka",
            "BirthName": "Anna Butka",
            "Privacy_IsPrivate": false,
            "Privacy_IsPublic": false,
            "Privacy_IsOpen": true,
            "Privacy_IsAtLeastPublic": true,
            "Privacy_IsSemiPrivate": false,
            "Privacy_IsSemiPrivateBio": false
          },
          {
            "Id": "10147688",
            "Name": "Zierak-3",
            "FirstName": "Helen Gertrude",
            "MiddleName": "",
            "LastNameAtBirth": "Zierak",
            "LastNameCurrent": "Zierak",
            "Nicknames": null,
            "LastNameOther": null,
            "RealName": "Helen Gertrude",
            "Prefix": null,
            "Suffix": null,
            "BirthLocation": null,
            "DeathLocation": null,
            "Gender": "Female",
            "BirthDate": "1896-02-07",
            "DeathDate": "1970-11-24",
            "BirthDateDecade": "1890's",
            "DeathDateDecade": "1970's",
            "Photo": "",
            "IsLiving": null,
            "Father": "10147689",
            "Mother": "10147690",
            "Privacy": "60",
            "IsPerson": 1,
            "Touched": "20150504144641",
            "ShortName": "Helen Gertrude Zierak",
            "BirthNamePrivate": "Helen Gertrude Zierak",
            "LongNamePrivate": "Helen Gertrude Zierak",
            "LongName": "Helen Gertrude  Zierak",
            "BirthName": "Helen Gertrude Zierak",
            "Privacy_IsPrivate": false,
            "Privacy_IsPublic": false,
            "Privacy_IsOpen": true,
            "Privacy_IsAtLeastPublic": true,
            "Privacy_IsSemiPrivate": false,
            "Privacy_IsSemiPrivateBio": false
          },
          {
            "Id": "10147689",
            "Name": "Zierak-4",
            "FirstName": "Albert John",
            "MiddleName": "",
            "LastNameAtBirth": "Zierak",
            "LastNameCurrent": "Zierak",
            "Nicknames": null,
            "LastNameOther": null,
            "RealName": "Albert John",
            "Prefix": null,
            "Suffix": null,
            "BirthLocation": null,
            "DeathLocation": null,
            "Gender": "Male",
            "BirthDate": "1860-04-04",
            "DeathDate": "1951-03-26",
            "BirthDateDecade": "1860's",
            "DeathDateDecade": "1950's",
            "Photo": "",
            "IsLiving": null,
            "Father": "10147716",
            "Mother": "10147717",
            "Privacy": "60",
            "IsPerson": 1,
            "Touched": "20150504144641",
            "ShortName": "Albert John Zierak",
            "BirthNamePrivate": "Albert John Zierak",
            "LongNamePrivate": "Albert John Zierak",
            "LongName": "Albert John  Zierak",
            "BirthName": "Albert John Zierak",
            "Privacy_IsPrivate": false,
            "Privacy_IsPublic": false,
            "Privacy_IsOpen": true,
            "Privacy_IsAtLeastPublic": true,
            "Privacy_IsSemiPrivate": false,
            "Privacy_IsSemiPrivateBio": false
          },
          {
            "Id": "10147716",
            "Name": "Zierak-14",
            "FirstName": "Andrew",
            "MiddleName": "",
            "LastNameAtBirth": "Zierak",
            "LastNameCurrent": "Zierak",
            "Nicknames": null,
            "LastNameOther": null,
            "RealName": "Andrew",
            "Prefix": null,
            "Suffix": null,
            "BirthLocation": null,
            "DeathLocation": null,
            "Gender": "Male",
            "BirthDate": "1823-11-27",
            "DeathDate": "0000-00-00",
            "BirthDateDecade": "1820's",
            "DeathDateDecade": "unknown",
            "Photo": "",
            "IsLiving": null,
            "Father": "10147748",
            "Mother": "10147751",
            "Privacy": "60",
            "IsPerson": 1,
            "Touched": "20150504144641",
            "ShortName": "Andrew Zierak",
            "BirthNamePrivate": "Andrew Zierak",
            "LongNamePrivate": "Andrew Zierak",
            "LongName": "Andrew  Zierak",
            "BirthName": "Andrew Zierak",
            "Privacy_IsPrivate": false,
            "Privacy_IsPublic": false,
            "Privacy_IsOpen": true,
            "Privacy_IsAtLeastPublic": true,
            "Privacy_IsSemiPrivate": false,
            "Privacy_IsSemiPrivateBio": false
          },
          {
            "Id": "10147748",
            "Name": "Zierak-16",
            "FirstName": "Wojciech",
            "MiddleName": "",
            "LastNameAtBirth": "Zierak",
            "LastNameCurrent": "Zierak",
            "Nicknames": null,
            "LastNameOther": null,
            "RealName": "Wojciech",
            "Prefix": null,
            "Suffix": null,
            "BirthLocation": null,
            "DeathLocation": null,
            "Gender": "Male",
            "BirthDate": "1786-04-01",
            "DeathDate": "1832-02-02",
            "BirthDateDecade": "1780's",
            "DeathDateDecade": "1830's",
            "Photo": "",
            "IsLiving": null,
            "Father": null,
            "Mother": null,
            "Privacy": "60",
            "IsPerson": 1,
            "Touched": "20150504144641",
            "ShortName": "Wojciech Zierak",
            "BirthNamePrivate": "Wojciech Zierak",
            "LongNamePrivate": "Wojciech Zierak",
            "LongName": "Wojciech  Zierak",
            "BirthName": "Wojciech Zierak",
            "Privacy_IsPrivate": false,
            "Privacy_IsPublic": false,
            "Privacy_IsOpen": true,
            "Privacy_IsAtLeastPublic": true,
            "Privacy_IsSemiPrivate": false,
            "Privacy_IsSemiPrivateBio": false
          },
          {
            "Id": "10147751",
            "Name": "Knapik-31",
            "FirstName": "Anna",
            "MiddleName": "",
            "LastNameAtBirth": "Knapik",
            "LastNameCurrent": "Knapik",
            "Nicknames": null,
            "LastNameOther": null,
            "RealName": "Anna",
            "Prefix": null,
            "Suffix": null,
            "BirthLocation": null,
            "DeathLocation": null,
            "Gender": "Female",
            "BirthDate": "1784-00-00",
            "DeathDate": "1832-02-13",
            "BirthDateDecade": "1780's",
            "DeathDateDecade": "1830's",
            "Photo": "",
            "IsLiving": null,
            "Father": "0",
            "Mother": "0",
            "Privacy": "60",
            "IsPerson": 1,
            "Touched": "20150504144641",
            "ShortName": "Anna Knapik",
            "BirthNamePrivate": "Anna Knapik",
            "LongNamePrivate": "Anna Knapik",
            "LongName": "Anna  Knapik",
            "BirthName": "Anna Knapik",
            "Privacy_IsPrivate": false,
            "Privacy_IsPublic": false,
            "Privacy_IsOpen": true,
            "Privacy_IsAtLeastPublic": true,
            "Privacy_IsSemiPrivate": false,
            "Privacy_IsSemiPrivateBio": false
          },
          {
            "Id": "10147717",
            "Name": "Zierak-15",
            "FirstName": "Katherine",
            "MiddleName": "",
            "LastNameAtBirth": "Zierak",
            "LastNameCurrent": "Zierak",
            "Nicknames": null,
            "LastNameOther": null,
            "RealName": "Katherine",
            "Prefix": null,
            "Suffix": null,
            "BirthLocation": null,
            "DeathLocation": null,
            "Gender": "Female",
            "BirthDate": "1822-03-24",
            "DeathDate": "1911-04-23",
            "BirthDateDecade": "1820's",
            "DeathDateDecade": "1910's",
            "Photo": "",
            "IsLiving": null,
            "Father": "10200771",
            "Mother": "10200773",
            "Privacy": "60",
            "IsPerson": 1,
            "Touched": "20150504144641",
            "ShortName": "Katherine Zierak",
            "BirthNamePrivate": "Katherine Zierak",
            "LongNamePrivate": "Katherine Zierak",
            "LongName": "Katherine  Zierak",
            "BirthName": "Katherine Zierak",
            "Privacy_IsPrivate": false,
            "Privacy_IsPublic": false,
            "Privacy_IsOpen": true,
            "Privacy_IsAtLeastPublic": true,
            "Privacy_IsSemiPrivate": false,
            "Privacy_IsSemiPrivateBio": false
          },
          {
            "Id": "10200771",
            "Name": "Zierak-39",
            "FirstName": "Maciej",
            "MiddleName": null,
            "LastNameAtBirth": "Zierak",
            "LastNameCurrent": "Zierak",
            "Nicknames": null,
            "LastNameOther": null,
            "RealName": "Maciej",
            "Prefix": null,
            "Suffix": null,
            "BirthLocation": null,
            "DeathLocation": null,
            "Gender": "Male",
            "BirthDate": "1780-00-00",
            "DeathDate": "0000-00-00",
            "BirthDateDecade": "1780's",
            "DeathDateDecade": "unknown",
            "Photo": null,
            "IsLiving": null,
            "Father": null,
            "Mother": null,
            "Privacy": "60",
            "IsPerson": 1,
            "Touched": "20150504144641",
            "ShortName": "Maciej Zierak",
            "BirthNamePrivate": "Maciej Zierak",
            "LongNamePrivate": "Maciej Zierak",
            "LongName": "Maciej  Zierak",
            "BirthName": "Maciej Zierak",
            "Privacy_IsPrivate": false,
            "Privacy_IsPublic": false,
            "Privacy_IsOpen": true,
            "Privacy_IsAtLeastPublic": true,
            "Privacy_IsSemiPrivate": false,
            "Privacy_IsSemiPrivateBio": false
          },
          {
            "Id": "10200773",
            "Name": "Wójcik-86",
            "FirstName": "Jadwiga",
            "MiddleName": null,
            "LastNameAtBirth": "Wójcik",
            "LastNameCurrent": "Wójcik",
            "Nicknames": null,
            "LastNameOther": null,
            "RealName": "Jadwiga",
            "Prefix": null,
            "Suffix": null,
            "BirthLocation": null,
            "DeathLocation": null,
            "Gender": "Female",
            "BirthDate": "1780-00-00",
            "DeathDate": "0000-00-00",
            "BirthDateDecade": "1780's",
            "DeathDateDecade": "unknown",
            "Photo": null,
            "IsLiving": null,
            "Father": null,
            "Mother": null,
            "Privacy": "60",
            "IsPerson": 1,
            "Touched": "20150504144641",
            "ShortName": "Jadwiga Wójcik",
            "BirthNamePrivate": "Jadwiga Wójcik",
            "LongNamePrivate": "Jadwiga Wójcik",
            "LongName": "Jadwiga  Wójcik",
            "BirthName": "Jadwiga Wójcik",
            "Privacy_IsPrivate": false,
            "Privacy_IsPublic": false,
            "Privacy_IsOpen": true,
            "Privacy_IsAtLeastPublic": true,
            "Privacy_IsSemiPrivate": false,
            "Privacy_IsSemiPrivateBio": false
          },
          {
            "Id": "10147690",
            "Name": "Wojnowski-3",
            "FirstName": "Mary",
            "MiddleName": "",
            "LastNameAtBirth": "Wojnowski",
            "LastNameCurrent": "Wojnowski",
            "Nicknames": null,
            "LastNameOther": null,
            "RealName": "Mary",
            "Prefix": null,
            "Suffix": null,
            "BirthLocation": null,
            "DeathLocation": null,
            "Gender": "Female",
            "BirthDate": "1863-00-00",
            "DeathDate": "1939-10-14",
            "BirthDateDecade": "1860's",
            "DeathDateDecade": "1930's",
            "Photo": "",
            "IsLiving": null,
            "Father": "10147702",
            "Mother": "10147704",
            "Privacy": "60",
            "IsPerson": 1,
            "Touched": "20150504144641",
            "ShortName": "Mary Wojnowski",
            "BirthNamePrivate": "Mary Wojnowski",
            "LongNamePrivate": "Mary Wojnowski",
            "LongName": "Mary  Wojnowski",
            "BirthName": "Mary Wojnowski",
            "Privacy_IsPrivate": false,
            "Privacy_IsPublic": false,
            "Privacy_IsOpen": true,
            "Privacy_IsAtLeastPublic": true,
            "Privacy_IsSemiPrivate": false,
            "Privacy_IsSemiPrivateBio": false
          },
          {
            "Id": "10147702",
            "Name": "Vannoske-1",
            "FirstName": "Joseph",
            "MiddleName": "",
            "LastNameAtBirth": "Vannoske",
            "LastNameCurrent": "Vannoske",
            "Nicknames": null,
            "LastNameOther": null,
            "RealName": "Joseph",
            "Prefix": null,
            "Suffix": null,
            "BirthLocation": null,
            "DeathLocation": null,
            "Gender": "Male",
            "BirthDate": "1825-00-00",
            "DeathDate": "0000-00-00",
            "BirthDateDecade": "1820's",
            "DeathDateDecade": "unknown",
            "Photo": "",
            "IsLiving": null,
            "Father": "0",
            "Mother": "0",
            "Privacy": "60",
            "IsPerson": 1,
            "Touched": "20150504144641",
            "ShortName": "Joseph Vannoske",
            "BirthNamePrivate": "Joseph Vannoske",
            "LongNamePrivate": "Joseph Vannoske",
            "LongName": "Joseph  Vannoske",
            "BirthName": "Joseph Vannoske",
            "Privacy_IsPrivate": false,
            "Privacy_IsPublic": false,
            "Privacy_IsOpen": true,
            "Privacy_IsAtLeastPublic": true,
            "Privacy_IsSemiPrivate": false,
            "Privacy_IsSemiPrivateBio": false
          },
          {
            "Id": "10147704",
            "Name": "UNKNOWN-274879",
            "FirstName": "Ida",
            "MiddleName": "",
            "LastNameAtBirth": "UNKNOWN",
            "LastNameCurrent": "UNKNOWN",
            "Nicknames": null,
            "LastNameOther": null,
            "RealName": "Ida",
            "Prefix": null,
            "Suffix": null,
            "BirthLocation": null,
            "DeathLocation": null,
            "Gender": "Female",
            "BirthDate": "1844-03-00",
            "DeathDate": "1926-09-00",
            "BirthDateDecade": "1840's",
            "DeathDateDecade": "1920's",
            "Photo": "",
            "IsLiving": null,
            "Father": "0",
            "Mother": "0",
            "Privacy": "60",
            "IsPerson": 1,
            "Touched": "20150504144641",
            "ShortName": "Ida UNKNOWN",
            "BirthNamePrivate": "Ida UNKNOWN",
            "LongNamePrivate": "Ida UNKNOWN",
            "LongName": "Ida  UNKNOWN",
            "BirthName": "Ida UNKNOWN",
            "Privacy_IsPrivate": false,
            "Privacy_IsPublic": false,
            "Privacy_IsOpen": true,
            "Privacy_IsAtLeastPublic": true,
            "Privacy_IsSemiPrivate": false,
            "Privacy_IsSemiPrivateBio": false
          }
        ],
        "status": 0
      }
    ];
  }
};