module.exports = function(opts){
    return [{
    	"user_name": "Wojnowski-3",
    	"person": {
    		"Id": 10147690,
    		"Name": "Wojnowski-3",
    		"FirstName": "Mary",
    		"MiddleName": "",
    		"LastNameAtBirth": "Wojnowski",
    		"LastNameCurrent": "Wojnowski",
    		"Nicknames": "",
    		"LastNameOther": "",
    		"RealName": "Mary",
    		"Prefix": "",
    		"Suffix": "",
    		"BirthLocation": "Pozna\u0144, Poland",
    		"DeathLocation": "Amsterdam, Montgomery, New York, United States",
    		"Gender": "Female",
    		"BirthDate": "1863-00-00",
    		"DeathDate": "1939-10-14",
    		"BirthDateDecade": "1860's",
    		"DeathDateDecade": "1930's",
    		"Photo": "",
    		"IsLiving": "0",
    		"Father": "10147702",
    		"Mother": "10147704",
    		"Privacy": "60",
    		"Parents": {
    			"10147702": {
    				"Id": 10147702,
    				"Name": "Vannoske-1",
    				"FirstName": "Joseph",
    				"MiddleName": "",
    				"LastNameAtBirth": "Vannoske",
    				"LastNameCurrent": "Vannoske",
    				"Nicknames": "",
    				"LastNameOther": "",
    				"RealName": "Joseph",
    				"Prefix": "",
    				"Suffix": "",
    				"BirthLocation": "PRUSSIA",
    				"DeathLocation": "",
    				"Gender": "Male",
    				"BirthDate": "1825-00-00",
    				"DeathDate": "0000-00-00",
    				"BirthDateDecade": "1820's",
    				"DeathDateDecade": "unknown",
    				"Photo": "",
    				"IsLiving": "0",
    				"Father": 0,
    				"Mother": 0,
    				"Privacy": "60",
    				"ShortName": "Joseph Vannoske",
    				"BirthNamePrivate": "Joseph Vannoske",
    				"LongNamePrivate": "Joseph Vannoske",
    				"LongName": "Joseph  Vannoske",
    				"BirthName": "Joseph Vannoske",
    				"Privacy_IsPrivate": false,
    				"Privacy_IsPublic": false,
    				"Privacy_IsOpen": true,
    				"Privacy_IsAtLeastPublic": true,
    				"Privacy_IsSemiPrivate": false,
    				"Privacy_IsSemiPrivateBio": false
    			},
    			"10147704": {
    				"Id": 10147704,
    				"Name": "UNKNOWN-274879",
    				"FirstName": "Ida",
    				"MiddleName": "",
    				"LastNameAtBirth": "UNKNOWN",
    				"LastNameCurrent": "UNKNOWN",
    				"Nicknames": "",
    				"LastNameOther": "",
    				"RealName": "Ida",
    				"Prefix": "",
    				"Suffix": "",
    				"BirthLocation": "Poland Ger",
    				"DeathLocation": "",
    				"Gender": "Female",
    				"BirthDate": "1844-03-00",
    				"DeathDate": "1926-09-00",
    				"BirthDateDecade": "1840's",
    				"DeathDateDecade": "1920's",
    				"Photo": "",
    				"IsLiving": "0",
    				"Father": 0,
    				"Mother": 0,
    				"Privacy": "60",
    				"ShortName": "Ida UNKNOWN",
    				"BirthNamePrivate": "Ida UNKNOWN",
    				"LongNamePrivate": "Ida UNKNOWN",
    				"LongName": "Ida  UNKNOWN",
    				"BirthName": "Ida UNKNOWN",
    				"Privacy_IsPrivate": false,
    				"Privacy_IsPublic": false,
    				"Privacy_IsOpen": true,
    				"Privacy_IsAtLeastPublic": true,
    				"Privacy_IsSemiPrivate": false,
    				"Privacy_IsSemiPrivateBio": false
    			}
    		},
    		"Siblings": {
    			"10147734": {
    				"Id": "10147734",
    				"Name": "VanNoske-4",
    				"FirstName": "Andrew",
    				"MiddleName": "",
    				"LastNameAtBirth": "VanNoske",
    				"LastNameCurrent": "VanNoske",
    				"Nicknames": "",
    				"LastNameOther": "",
    				"RealName": "Andrew",
    				"Prefix": "",
    				"Suffix": "",
    				"BirthLocation": "Poland Ger",
    				"DeathLocation": "Amsterdam, Montgomery, New York, United States",
    				"Gender": "Male",
    				"BirthDate": "1866-10-00",
    				"DeathDate": "1914-02-04",
    				"BirthDateDecade": "1860's",
    				"DeathDateDecade": "1910's",
    				"Photo": "",
    				"IsLiving": "0",
    				"Father": "10147702",
    				"Mother": "10147704",
    				"Privacy": "60",
    				"ShortName": "Andrew VanNoske",
    				"BirthNamePrivate": "Andrew VanNoske",
    				"LongNamePrivate": "Andrew VanNoske",
    				"LongName": "Andrew  VanNoske",
    				"BirthName": "Andrew VanNoske",
    				"Privacy_IsPrivate": false,
    				"Privacy_IsPublic": false,
    				"Privacy_IsOpen": true,
    				"Privacy_IsAtLeastPublic": true,
    				"Privacy_IsSemiPrivate": false,
    				"Privacy_IsSemiPrivateBio": false
    			},
    			"10147732": {
    				"Id": "10147732",
    				"Name": "Vannoske-3",
    				"FirstName": "Katherine",
    				"MiddleName": "",
    				"LastNameAtBirth": "Vannoske",
    				"LastNameCurrent": "Vannoske",
    				"Nicknames": "",
    				"LastNameOther": "",
    				"RealName": "Katherine",
    				"Prefix": "",
    				"Suffix": "",
    				"BirthLocation": "New York",
    				"DeathLocation": "",
    				"Gender": "Female",
    				"BirthDate": "1876-10-00",
    				"DeathDate": "1945-03-23",
    				"BirthDateDecade": "1870's",
    				"DeathDateDecade": "1940's",
    				"Photo": "",
    				"IsLiving": "0",
    				"Father": "10147702",
    				"Mother": "10147704",
    				"Privacy": "60",
    				"ShortName": "Katherine Vannoske",
    				"BirthNamePrivate": "Katherine Vannoske",
    				"LongNamePrivate": "Katherine Vannoske",
    				"LongName": "Katherine  Vannoske",
    				"BirthName": "Katherine Vannoske",
    				"Privacy_IsPrivate": false,
    				"Privacy_IsPublic": false,
    				"Privacy_IsOpen": true,
    				"Privacy_IsAtLeastPublic": true,
    				"Privacy_IsSemiPrivate": false,
    				"Privacy_IsSemiPrivateBio": false
    			},
    			"10147729": {
    				"Id": "10147729",
    				"Name": "Vannoske-2",
    				"FirstName": "Fanny",
    				"MiddleName": "",
    				"LastNameAtBirth": "Vannoske",
    				"LastNameCurrent": "Vannoske",
    				"Nicknames": "",
    				"LastNameOther": "",
    				"RealName": "Fanny",
    				"Prefix": "",
    				"Suffix": "",
    				"BirthLocation": "NY",
    				"DeathLocation": "",
    				"Gender": "Female",
    				"BirthDate": "1877-00-00",
    				"DeathDate": "0000-00-00",
    				"BirthDateDecade": "1870's",
    				"DeathDateDecade": "unknown",
    				"Photo": "",
    				"IsLiving": "0",
    				"Father": "10147702",
    				"Mother": "10147704",
    				"Privacy": "60",
    				"ShortName": "Fanny Vannoske",
    				"BirthNamePrivate": "Fanny Vannoske",
    				"LongNamePrivate": "Fanny Vannoske",
    				"LongName": "Fanny  Vannoske",
    				"BirthName": "Fanny Vannoske",
    				"Privacy_IsPrivate": false,
    				"Privacy_IsPublic": false,
    				"Privacy_IsOpen": true,
    				"Privacy_IsAtLeastPublic": true,
    				"Privacy_IsSemiPrivate": false,
    				"Privacy_IsSemiPrivateBio": false
    			},
    			"10147736": {
    				"Id": "10147736",
    				"Name": "Van Noske-2",
    				"FirstName": "Frank",
    				"MiddleName": "",
    				"LastNameAtBirth": "Van Noske",
    				"LastNameCurrent": "Van Noske",
    				"Nicknames": "",
    				"LastNameOther": "",
    				"RealName": "Frank",
    				"Prefix": "",
    				"Suffix": "",
    				"BirthLocation": "Switzer Hill, Fonda, Montgomery, New York, United States",
    				"DeathLocation": "Niskayuna, Schenectady, New York, United States",
    				"Gender": "Male",
    				"BirthDate": "1878-09-26",
    				"DeathDate": "1944-11-17",
    				"BirthDateDecade": "1870's",
    				"DeathDateDecade": "1940's",
    				"Photo": "",
    				"IsLiving": "0",
    				"Father": "10147702",
    				"Mother": "10147704",
    				"Privacy": "60",
    				"ShortName": "Frank Van Noske",
    				"BirthNamePrivate": "Frank Van Noske",
    				"LongNamePrivate": "Frank Van Noske",
    				"LongName": "Frank  Van Noske",
    				"BirthName": "Frank Van Noske",
    				"Privacy_IsPrivate": false,
    				"Privacy_IsPublic": false,
    				"Privacy_IsOpen": true,
    				"Privacy_IsAtLeastPublic": true,
    				"Privacy_IsSemiPrivate": false,
    				"Privacy_IsSemiPrivateBio": false
    			},
    			"10147731": {
    				"Id": "10147731",
    				"Name": "Vanoske-1",
    				"FirstName": "Antoinett",
    				"MiddleName": "",
    				"LastNameAtBirth": "Vanoske",
    				"LastNameCurrent": "Vanoske",
    				"Nicknames": "",
    				"LastNameOther": "",
    				"RealName": "Antoinett",
    				"Prefix": "",
    				"Suffix": "",
    				"BirthLocation": "New York, United States",
    				"DeathLocation": "Rome, Oneida, New York, United States",
    				"Gender": "Female",
    				"BirthDate": "1881-02-00",
    				"DeathDate": "1929-05-18",
    				"BirthDateDecade": "1880's",
    				"DeathDateDecade": "1920's",
    				"Photo": "",
    				"IsLiving": "0",
    				"Father": "10147702",
    				"Mother": "10147704",
    				"Privacy": "60",
    				"ShortName": "Antoinett Vanoske",
    				"BirthNamePrivate": "Antoinett Vanoske",
    				"LongNamePrivate": "Antoinett Vanoske",
    				"LongName": "Antoinett  Vanoske",
    				"BirthName": "Antoinett Vanoske",
    				"Privacy_IsPrivate": false,
    				"Privacy_IsPublic": false,
    				"Privacy_IsOpen": true,
    				"Privacy_IsAtLeastPublic": true,
    				"Privacy_IsSemiPrivate": false,
    				"Privacy_IsSemiPrivateBio": false
    			},
    			"10147735": {
    				"Id": "10147735",
    				"Name": "Van Noske-1",
    				"FirstName": "Lucy",
    				"MiddleName": "",
    				"LastNameAtBirth": "Van Noske",
    				"LastNameCurrent": "Van Noske",
    				"Nicknames": "",
    				"LastNameOther": "",
    				"RealName": "Lucy",
    				"Prefix": "",
    				"Suffix": "",
    				"BirthLocation": "New York",
    				"DeathLocation": "Albany, New York",
    				"Gender": "Female",
    				"BirthDate": "1884-02-00",
    				"DeathDate": "0000-00-00",
    				"BirthDateDecade": "1880's",
    				"DeathDateDecade": "unknown",
    				"Photo": "",
    				"IsLiving": "0",
    				"Father": "10147702",
    				"Mother": "10147704",
    				"Privacy": "60",
    				"ShortName": "Lucy Van Noske",
    				"BirthNamePrivate": "Lucy Van Noske",
    				"LongNamePrivate": "Lucy Van Noske",
    				"LongName": "Lucy  Van Noske",
    				"BirthName": "Lucy Van Noske",
    				"Privacy_IsPrivate": false,
    				"Privacy_IsPublic": false,
    				"Privacy_IsOpen": true,
    				"Privacy_IsAtLeastPublic": true,
    				"Privacy_IsSemiPrivate": false,
    				"Privacy_IsSemiPrivateBio": false
    			},
    			"10147733": {
    				"Id": "10147733",
    				"Name": "Gunia-2",
    				"FirstName": "Sophia",
    				"MiddleName": "",
    				"LastNameAtBirth": "Gunia",
    				"LastNameCurrent": "Gunia",
    				"Nicknames": "",
    				"LastNameOther": "",
    				"RealName": "Sophia",
    				"Prefix": "",
    				"Suffix": "",
    				"BirthLocation": "Poland Aust",
    				"DeathLocation": "",
    				"Gender": "Female",
    				"BirthDate": "1890-03-00",
    				"DeathDate": "0000-00-00",
    				"BirthDateDecade": "1890's",
    				"DeathDateDecade": "unknown",
    				"Photo": "",
    				"IsLiving": "0",
    				"Father": "10147702",
    				"Mother": "10147704",
    				"Privacy": "60",
    				"ShortName": "Sophia Gunia",
    				"BirthNamePrivate": "Sophia Gunia",
    				"LongNamePrivate": "Sophia Gunia",
    				"LongName": "Sophia  Gunia",
    				"BirthName": "Sophia Gunia",
    				"Privacy_IsPrivate": false,
    				"Privacy_IsPublic": false,
    				"Privacy_IsOpen": true,
    				"Privacy_IsAtLeastPublic": true,
    				"Privacy_IsSemiPrivate": false,
    				"Privacy_IsSemiPrivateBio": false
    			}
    		},
    		"Spouses": {
    			"10147689": {
    				"Id": 10147689,
    				"Name": "Zierak-4",
    				"FirstName": "Albert John",
    				"MiddleName": "",
    				"LastNameAtBirth": "Zierak",
    				"LastNameCurrent": "Zierak",
    				"Nicknames": "",
    				"LastNameOther": "",
    				"RealName": "Albert John",
    				"Prefix": "",
    				"Suffix": "",
    				"BirthLocation": "Lipinki, Gorlice, Poland",
    				"DeathLocation": "Amsterdam, Montgomery, New York, United States",
    				"Gender": "Male",
    				"BirthDate": "1860-04-04",
    				"DeathDate": "1951-03-26",
    				"BirthDateDecade": "1860's",
    				"DeathDateDecade": "1950's",
    				"Photo": "",
    				"IsLiving": "0",
    				"Father": "10147716",
    				"Mother": "10147717",
    				"Privacy": "60",
    				"ShortName": "Albert John Zierak",
    				"BirthNamePrivate": "Albert John Zierak",
    				"LongNamePrivate": "Albert John Zierak",
    				"LongName": "Albert John  Zierak",
    				"BirthName": "Albert John Zierak",
    				"Privacy_IsPrivate": false,
    				"Privacy_IsPublic": false,
    				"Privacy_IsOpen": true,
    				"Privacy_IsAtLeastPublic": true,
    				"Privacy_IsSemiPrivate": false,
    				"Privacy_IsSemiPrivateBio": false,
    				"marriage_location": "United States",
    				"marriage_date": "1886-00-00",
    				"marriage_end_date": "0000-00-00",
    				"do_not_display": "0"
    			}
    		},
    		"Children": {
    			"10147710": {
    				"Id": "10147710",
    				"Name": "Zierak-10",
    				"FirstName": "Catherine",
    				"MiddleName": "",
    				"LastNameAtBirth": "Zierak",
    				"LastNameCurrent": "Zierak",
    				"Nicknames": "",
    				"LastNameOther": "",
    				"RealName": "Catherine",
    				"Prefix": "",
    				"Suffix": "",
    				"BirthLocation": "Amsterdam, Montgomery, New York, United States",
    				"DeathLocation": "Amsterdam, Montgomery, New York, United States",
    				"Gender": "Female",
    				"BirthDate": "1887-10-24",
    				"DeathDate": "1949-07-00",
    				"BirthDateDecade": "1880's",
    				"DeathDateDecade": "1940's",
    				"Photo": "",
    				"IsLiving": "0",
    				"Father": "10147689",
    				"Mother": "10147690",
    				"Privacy": "60",
    				"ShortName": "Catherine Zierak",
    				"BirthNamePrivate": "Catherine Zierak",
    				"LongNamePrivate": "Catherine Zierak",
    				"LongName": "Catherine  Zierak",
    				"BirthName": "Catherine Zierak",
    				"Privacy_IsPrivate": false,
    				"Privacy_IsPublic": false,
    				"Privacy_IsOpen": true,
    				"Privacy_IsAtLeastPublic": true,
    				"Privacy_IsSemiPrivate": false,
    				"Privacy_IsSemiPrivateBio": false
    			},
    			"10147709": {
    				"Id": "10147709",
    				"Name": "Zierak-9",
    				"FirstName": "Anna",
    				"MiddleName": "",
    				"LastNameAtBirth": "Zierak",
    				"LastNameCurrent": "Zierak",
    				"Nicknames": "",
    				"LastNameOther": "",
    				"RealName": "Anna",
    				"Prefix": "",
    				"Suffix": "",
    				"BirthLocation": "Amsterdam, Montgomery, New York, United States",
    				"DeathLocation": "Amsterdam, Montgomery, New York, United States",
    				"Gender": "Female",
    				"BirthDate": "1890-07-22",
    				"DeathDate": "1977-08-12",
    				"BirthDateDecade": "1890's",
    				"DeathDateDecade": "1970's",
    				"Photo": "",
    				"IsLiving": "0",
    				"Father": "10147689",
    				"Mother": "10147690",
    				"Privacy": "60",
    				"ShortName": "Anna Zierak",
    				"BirthNamePrivate": "Anna Zierak",
    				"LongNamePrivate": "Anna Zierak",
    				"LongName": "Anna  Zierak",
    				"BirthName": "Anna Zierak",
    				"Privacy_IsPrivate": false,
    				"Privacy_IsPublic": false,
    				"Privacy_IsOpen": true,
    				"Privacy_IsAtLeastPublic": true,
    				"Privacy_IsSemiPrivate": false,
    				"Privacy_IsSemiPrivateBio": false
    			},
    			"10147712": {
    				"Id": "10147712",
    				"Name": "Zierak-12",
    				"FirstName": "John",
    				"MiddleName": "",
    				"LastNameAtBirth": "Zierak",
    				"LastNameCurrent": "Zierak",
    				"Nicknames": "",
    				"LastNameOther": "",
    				"RealName": "John",
    				"Prefix": "",
    				"Suffix": "",
    				"BirthLocation": "New York, United States",
    				"DeathLocation": "Seattle, King, Washington, United States",
    				"Gender": "Male",
    				"BirthDate": "1892-06-22",
    				"DeathDate": "1969-10-00",
    				"BirthDateDecade": "1890's",
    				"DeathDateDecade": "1960's",
    				"Photo": "",
    				"IsLiving": "0",
    				"Father": "10147689",
    				"Mother": "10147690",
    				"Privacy": "60",
    				"ShortName": "John Zierak",
    				"BirthNamePrivate": "John Zierak",
    				"LongNamePrivate": "John Zierak",
    				"LongName": "John  Zierak",
    				"BirthName": "John Zierak",
    				"Privacy_IsPrivate": false,
    				"Privacy_IsPublic": false,
    				"Privacy_IsOpen": true,
    				"Privacy_IsAtLeastPublic": true,
    				"Privacy_IsSemiPrivate": false,
    				"Privacy_IsSemiPrivateBio": false
    			},
    			"10147713": {
    				"Id": "10147713",
    				"Name": "Zierak-13",
    				"FirstName": "Stephen A",
    				"MiddleName": "",
    				"LastNameAtBirth": "Zierak",
    				"LastNameCurrent": "Zierak",
    				"Nicknames": "",
    				"LastNameOther": "",
    				"RealName": "Stephen A",
    				"Prefix": "",
    				"Suffix": "",
    				"BirthLocation": "Amsterdam, Montgomery, New York, United States",
    				"DeathLocation": "Bath, Steuben, New York, United States",
    				"Gender": "Male",
    				"BirthDate": "1894-03-22",
    				"DeathDate": "1961-04-07",
    				"BirthDateDecade": "1890's",
    				"DeathDateDecade": "1960's",
    				"Photo": "",
    				"IsLiving": "0",
    				"Father": "10147689",
    				"Mother": "10147690",
    				"Privacy": "60",
    				"ShortName": "Stephen A Zierak",
    				"BirthNamePrivate": "Stephen A Zierak",
    				"LongNamePrivate": "Stephen A Zierak",
    				"LongName": "Stephen A  Zierak",
    				"BirthName": "Stephen A Zierak",
    				"Privacy_IsPrivate": false,
    				"Privacy_IsPublic": false,
    				"Privacy_IsOpen": true,
    				"Privacy_IsAtLeastPublic": true,
    				"Privacy_IsSemiPrivate": false,
    				"Privacy_IsSemiPrivateBio": false
    			},
    			"10147688": {
    				"Id": "10147688",
    				"Name": "Zierak-3",
    				"FirstName": "Helen Gertrude",
    				"MiddleName": "",
    				"LastNameAtBirth": "Zierak",
    				"LastNameCurrent": "Zierak",
    				"Nicknames": "",
    				"LastNameOther": "",
    				"RealName": "Helen Gertrude",
    				"Prefix": "",
    				"Suffix": "",
    				"BirthLocation": "Amsterdam, Montgomery, New York, United States",
    				"DeathLocation": "Tacoma, Pierce, Washington, United States",
    				"Gender": "Female",
    				"BirthDate": "1896-02-07",
    				"DeathDate": "1970-11-24",
    				"BirthDateDecade": "1890's",
    				"DeathDateDecade": "1970's",
    				"Photo": "",
    				"IsLiving": "0",
    				"Father": "10147689",
    				"Mother": "10147690",
    				"Privacy": "60",
    				"ShortName": "Helen Gertrude Zierak",
    				"BirthNamePrivate": "Helen Gertrude Zierak",
    				"LongNamePrivate": "Helen Gertrude Zierak",
    				"LongName": "Helen Gertrude  Zierak",
    				"BirthName": "Helen Gertrude Zierak",
    				"Privacy_IsPrivate": false,
    				"Privacy_IsPublic": false,
    				"Privacy_IsOpen": true,
    				"Privacy_IsAtLeastPublic": true,
    				"Privacy_IsSemiPrivate": false,
    				"Privacy_IsSemiPrivateBio": false
    			},
    			"10147708": {
    				"Id": "10147708",
    				"Name": "Zierak-8",
    				"FirstName": "Andrew Joseph",
    				"MiddleName": "",
    				"LastNameAtBirth": "Zierak",
    				"LastNameCurrent": "Zierak",
    				"Nicknames": "",
    				"LastNameOther": "",
    				"RealName": "Andrew Joseph",
    				"Prefix": "",
    				"Suffix": "",
    				"BirthLocation": "New York, United States",
    				"DeathLocation": "Amsterdam, Montgomery, New York, United States",
    				"Gender": "Male",
    				"BirthDate": "1898-06-14",
    				"DeathDate": "1965-10-24",
    				"BirthDateDecade": "1890's",
    				"DeathDateDecade": "1960's",
    				"Photo": "",
    				"IsLiving": "0",
    				"Father": "10147689",
    				"Mother": "10147690",
    				"Privacy": "60",
    				"ShortName": "Andrew Joseph Zierak",
    				"BirthNamePrivate": "Andrew Joseph Zierak",
    				"LongNamePrivate": "Andrew Joseph Zierak",
    				"LongName": "Andrew Joseph  Zierak",
    				"BirthName": "Andrew Joseph Zierak",
    				"Privacy_IsPrivate": false,
    				"Privacy_IsPublic": false,
    				"Privacy_IsOpen": true,
    				"Privacy_IsAtLeastPublic": true,
    				"Privacy_IsSemiPrivate": false,
    				"Privacy_IsSemiPrivateBio": false
    			},
    			"10147706": {
    				"Id": "10147706",
    				"Name": "Zierak-6",
    				"FirstName": "Josephine",
    				"MiddleName": "",
    				"LastNameAtBirth": "Zierak",
    				"LastNameCurrent": "Zierak",
    				"Nicknames": "",
    				"LastNameOther": "",
    				"RealName": "Josephine",
    				"Prefix": "",
    				"Suffix": "",
    				"BirthLocation": "Amsterdam, Montgomery, New York, United States",
    				"DeathLocation": "Amsterdam, Montgomery, New York, United States",
    				"Gender": "Female",
    				"BirthDate": "1900-08-17",
    				"DeathDate": "1979-08-10",
    				"BirthDateDecade": "1900's",
    				"DeathDateDecade": "1970's",
    				"Photo": "",
    				"IsLiving": "0",
    				"Father": "10147689",
    				"Mother": "10147690",
    				"Privacy": "60",
    				"ShortName": "Josephine Zierak",
    				"BirthNamePrivate": "Josephine Zierak",
    				"LongNamePrivate": "Josephine Zierak",
    				"LongName": "Josephine  Zierak",
    				"BirthName": "Josephine Zierak",
    				"Privacy_IsPrivate": false,
    				"Privacy_IsPublic": false,
    				"Privacy_IsOpen": true,
    				"Privacy_IsAtLeastPublic": true,
    				"Privacy_IsSemiPrivate": false,
    				"Privacy_IsSemiPrivateBio": false
    			},
    			"10147705": {
    				"Id": "10147705",
    				"Name": "Zierak-5",
    				"FirstName": "Genevieve",
    				"MiddleName": "",
    				"LastNameAtBirth": "Zierak",
    				"LastNameCurrent": "Zierak",
    				"Nicknames": "",
    				"LastNameOther": "",
    				"RealName": "Genevieve",
    				"Prefix": "",
    				"Suffix": "",
    				"BirthLocation": "Amsterdam, Montgomery, New York, United States",
    				"DeathLocation": "Hudson Falls, Washington, New York, United States",
    				"Gender": "Female",
    				"BirthDate": "1902-10-01",
    				"DeathDate": "1973-05-11",
    				"BirthDateDecade": "1900's",
    				"DeathDateDecade": "1970's",
    				"Photo": "",
    				"IsLiving": "0",
    				"Father": "10147689",
    				"Mother": "10147690",
    				"Privacy": "60",
    				"ShortName": "Genevieve Zierak",
    				"BirthNamePrivate": "Genevieve Zierak",
    				"LongNamePrivate": "Genevieve Zierak",
    				"LongName": "Genevieve  Zierak",
    				"BirthName": "Genevieve Zierak",
    				"Privacy_IsPrivate": false,
    				"Privacy_IsPublic": false,
    				"Privacy_IsOpen": true,
    				"Privacy_IsAtLeastPublic": true,
    				"Privacy_IsSemiPrivate": false,
    				"Privacy_IsSemiPrivateBio": false
    			},
    			"10147707": {
    				"Id": "10147707",
    				"Name": "Zierak-7",
    				"FirstName": "Margaret",
    				"MiddleName": "",
    				"LastNameAtBirth": "Zierak",
    				"LastNameCurrent": "Zierak",
    				"Nicknames": "",
    				"LastNameOther": "",
    				"RealName": "Margaret",
    				"Prefix": "",
    				"Suffix": "",
    				"BirthLocation": "Amsterdam, Montgomery, New York, United States",
    				"DeathLocation": "Amsterdam, Montgomery, New York, United States",
    				"Gender": "Female",
    				"BirthDate": "1904-07-04",
    				"DeathDate": "1973-05-11",
    				"BirthDateDecade": "1900's",
    				"DeathDateDecade": "1970's",
    				"Photo": "",
    				"IsLiving": "0",
    				"Father": "10147689",
    				"Mother": "10147690",
    				"Privacy": "60",
    				"ShortName": "Margaret Zierak",
    				"BirthNamePrivate": "Margaret Zierak",
    				"LongNamePrivate": "Margaret Zierak",
    				"LongName": "Margaret  Zierak",
    				"BirthName": "Margaret Zierak",
    				"Privacy_IsPrivate": false,
    				"Privacy_IsPublic": false,
    				"Privacy_IsOpen": true,
    				"Privacy_IsAtLeastPublic": true,
    				"Privacy_IsSemiPrivate": false,
    				"Privacy_IsSemiPrivateBio": false
    			},
    			"10147711": {
    				"Id": "10147711",
    				"Name": "Zierak-11",
    				"FirstName": "Albert",
    				"MiddleName": "",
    				"LastNameAtBirth": "Zierak",
    				"LastNameCurrent": "Zierak",
    				"Nicknames": "",
    				"LastNameOther": "",
    				"RealName": "Albert",
    				"Prefix": "",
    				"Suffix": "II",
    				"BirthLocation": "Amsterdam, Montgomery, New York, United States",
    				"DeathLocation": "Amsterdam, Montgomery, New York, United States",
    				"Gender": "Male",
    				"BirthDate": "1908-06-23",
    				"DeathDate": "1979-12-29",
    				"BirthDateDecade": "1900's",
    				"DeathDateDecade": "1970's",
    				"Photo": "",
    				"IsLiving": "0",
    				"Father": "10147689",
    				"Mother": "10147690",
    				"Privacy": "60",
    				"ShortName": "Albert Zierak II",
    				"BirthNamePrivate": "Albert Zierak II",
    				"LongNamePrivate": "Albert Zierak II",
    				"LongName": "Albert  Zierak II",
    				"BirthName": "Albert Zierak II",
    				"Privacy_IsPrivate": false,
    				"Privacy_IsPublic": false,
    				"Privacy_IsOpen": true,
    				"Privacy_IsAtLeastPublic": true,
    				"Privacy_IsSemiPrivate": false,
    				"Privacy_IsSemiPrivateBio": false
    			}
    		},
    		"ShortName": "Mary Wojnowski",
    		"BirthNamePrivate": "Mary Wojnowski",
    		"LongNamePrivate": "Mary Wojnowski",
    		"LongName": "Mary  Wojnowski",
    		"BirthName": "Mary Wojnowski",
    		"Privacy_IsPrivate": false,
    		"Privacy_IsPublic": false,
    		"Privacy_IsOpen": true,
    		"Privacy_IsAtLeastPublic": true,
    		"Privacy_IsSemiPrivate": false,
    		"Privacy_IsSemiPrivateBio": false
    	},
    	"status": 0
    }];
};